export default NavigationConstants = {
  O_LEVEL: {
    ALL: 'ALL',
    QS: 'QS',
    MS: 'MS',
    SUBJECT: 'o-level-subjects',
    SUBJECT_TOPICAL: 'o-level-subjects-topical',
    YEARLY_TAB: 'o-levels-tab',
    TOPIC_FILTER: 'o-level-topics',
  },
  A_LEVEL: {
    ALL: 'ALL',
    QS: 'QS',
    MS: 'MS',
    SUBJECT: 'a-level-subjects',
    SUBJECT_TOPICAL: 'a-level-subjects-topical',
    YEARLY_TAB: 'a-levels-tab',
    TOPIC_FILTER: 'a-level-topics',
  },
  PAPERS: 'Papers',
  FORUM: 'Forum',
  TAB: 'Tab',
  YEARLY_PDF: `pdf`,
  CUSTOM_PAPERS: 'custom-papers',
};
